108: Added Authorization config.
osama004/ParkPal-Backend pull request #124
Opened 2024-09-14 20:03 UTC by Lucaww23e013

Added Authorization config. EndPoints have specific authorization now. Can be finilized later on tho.
Had to configure filterChain function like that, bc of checkstyle function limit.

2024-09-14 20:57 UTC, osama004 requested changes
3 Routes in AuthController are completely unnecessary  as this information is already in jwt token included. Also the check of currentUser in CustomAuthorizationManager is checking the same userId, so it is always true

2024-09-15 09:11 UTC, Lucaww23e013 commented
he method isCurrentUserOrAdmin takes two parameters: **Authentication** and **userId**. The **Authentication** object provides the UserPrincipal of the current user from the JWT, which includes the userId of the current user. The **userId** is extracted from the RequestAuthorizationContext, which encapsulates the context of an HTTP request and provides the userId from the request path.

**Example debug output:**
app-1    | obj {userId=c07cd7cb-ce44-4709-a9b6-9d8d2d568263}
app-1    | authentication: [Principal=at.technikum.parkpalbackend.security.principal.UserPrincipal@7e7583a8]
app-1    | obj-userId: c07cd7cb-ce44-4709-a9b6-9d8d2d568263
app-1    | auth-userPrincipal-id: c07cd7cb-ce44-4709-a9b6-9d8d2d568264
In this example, the current user (c07cd7cb-ce44-4709-a9b6-9d8d2d568264) is making an HTTP request for user c07cd7cb-ce44-4709-a9b6-9d8d2d568263.

The @GetMapping("/me") endpoint only provides details about the current user (userId, role) based on the JWT. It doesn't handle the authorization of the current user. The routes I implemented provide information about the authorization scenarios for specific endpoints for current user. These routes are used for debugging and provide useful information for authorization purposes.

2024-09-21 12:28 UTC, osama004 approved these changes

2024-10-04 10:58 UTC, osama004 approved these changes

2024-10-04 11:02 UTC, osama004 approved these changes

2024-10-04 11:02 UTC, merged